name: Node.js CI
#Workflow for testing newly pushed code to our repo
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - cd: server
      - touch: test/config.ts
      - run: npm run start --if-present
      - run: npm test
      - cd: ..

      - cd: client
      - run: npm run start --if-present
      - run: npm test
